AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kjell

  Sample SAM Template for kjell

Globals:
  Function:
    Timeout: 60
    MemorySize: 512

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kjell

  Sample SAM Template for kjell

Globals:
  Function:
    Timeout: 60
    MemorySize: 512

Resources:
  Bucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: kandidat2028

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          BUCKET_NAME: !Ref Bucket
      Policies:
        - AmazonRekognitionFullAccess
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: DevOpsExam/kjell/hello_world
            Method: get

  ImageBucketName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${Bucket}/imagebucketname"
      Type: String
      Value: !Ref Bucket
      Description: "S3 bucket name for storing images"

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn

  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn