name: Java Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: PowerShell/PowerShell@v2

      - name: Login to Amazon ECR
        env:
          AWS_REGION: 'eu-west-1'  # Update this with your AWS region
        run: |
          $password = (Get-ECRLoginCommand).Password | ConvertTo-SecureString -AsPlainText -Force
          $creds = New-Object System.Management.Automation.PSCredential -ArgumentList @("AWS", $password)
          docker login -u AWS -p $creds -e none https://244530008913.dkr.ecr.eu-west-1.amazonaws.com

      - name: Build and push Docker image to ECR
        env:
          AWS_REGION: 'eu-west-1'  # Update this with your AWS region
          ECR_REGISTRY: '244530008913.dkr.ecr.eu-west-1.amazonaws.com/ecrkandidat2028'
          IMAGE_NAME: 'ecrkandidat2028'  # Update this with your repository name
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          TAGS=("$ECR_REGISTRY/$IMAGE_NAME:$COMMIT_HASH" "$ECR_REGISTRY/$IMAGE_NAME:latest" "$ECR_REGISTRY/$IMAGE_NAME:main")

          echo "Building and pushing Docker image"
          docker build -t "${TAGS[0]}" .
          docker tag "${TAGS[0]}" "${TAGS[1]}"
          docker tag "${TAGS[0]}" "${TAGS[2]}"

          for tag in "${TAGS[@]}"; do
            docker push "$tag"
          done
