name: Java Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          ECR_REGISTRY="244530008913.dkr.ecr.eu-west-1.amazonaws.com/ecrkandidat2028"
          AWS_REGION="eu-west-1"
          
          
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}" | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build and push Docker image
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          ECR_REGISTRY="244530008913.dkr.ecr.eu-west-1.amazonaws.com/ecrkandidat2028"
          IMAGE_NAME="ecrkandidat2028"

          # Build and push Docker image
          docker build -t "$ECR_REGISTRY/$IMAGE_NAME:$COMMIT_HASH" .
          docker tag "$ECR_REGISTRY/$IMAGE_NAME:$COMMIT_HASH" "$ECR_REGISTRY/$IMAGE_NAME:latest"
          docker tag "$ECR_REGISTRY/$IMAGE_NAME:$COMMIT_HASH" "$ECR_REGISTRY/$IMAGE_NAME:main"
          docker push "$ECR_REGISTRY/$IMAGE_NAME:$COMMIT_HASH"
          docker push "$ECR_REGISTRY/$IMAGE_NAME:latest"
          docker push "$ECR_REGISTRY/$IMAGE_NAME:main"
