name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image to ECR
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      run: |
        COMMIT_HASH=$(git rev-parse --short HEAD)
        IMAGE_NAME=glenn-ppe

        echo "Logging in to Amazon ECR"
        echo $AWS_SECRET_ACCESS_KEY | docker login -u AWS --password-stdin $ECR_REGISTRY

        echo "Building and pushing Docker image"
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker buildx build --platform linux/amd64,linux/arm64 -t $ECR_REGISTRY/$IMAGE_NAME:$COMMIT_HASH -t $ECR_REGISTRY/$IMAGE_NAME:latest -t $ECR_REGISTRY/$IMAGE_NAME:main .

        echo "Pushing Docker image to ECR"
        docker push $ECR_REGISTRY/$IMAGE_NAME:$COMMIT_HASH
        docker push $ECR_REGISTRY/$IMAGE_NAME:latest
        docker push $ECR_REGISTRY/$IMAGE_NAME:main
