- name: Build and push Docker image to ECR
  env:
    AWS_REGION: 'eu-west-1'
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    ECR_REGISTRY: '244530008913.dkr.ecr.eu-west-1.amazonaws.com'
    IMAGE_NAME: 'ecrkandidat2028'
  run: |
    COMMIT_HASH=$(git rev-parse --short HEAD)
    TAGS=("$ECR_REGISTRY/$IMAGE_NAME:$COMMIT_HASH" "$ECR_REGISTRY/$IMAGE_NAME:latest" "$ECR_REGISTRY/$IMAGE_NAME:main")

    echo "Logging in to Amazon ECR"
    echo $AWS_SECRET_ACCESS_KEY | docker login -u AWS --password-stdin $ECR_REGISTRY

    echo "Building and pushing Docker image"
    docker buildx create --use
    docker buildx inspect --bootstrap
    docker buildx build --platform linux/amd64,linux/arm64 -t "${TAGS[@]}" .

    echo "Pushing Docker image to ECR"
    for tag in "${TAGS[@]}"; do
      docker push "$tag"
    done
