AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3

Resources:
  SentimentFunction:
    Type: AWS::Serverless::Function
    Auth:
      Authorizer: NONE
    Properties:
      CodeUri: lambda/
      Handler: app.handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.8
      Timeout: 10
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /sentiment
            Method: post
name: SAM Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Build and Deploy SAM Application
      if: github.ref == 'refs/heads/main'
      run: |
        sam build --template-file .github/workflows/samdeployment.yaml
        /usr/local/bin/sam deploy --stack-name DevOpsExam --region eu-west-1 --capabilities CAPABILITY_IAM --template-file .github/workflows/samdeployment.yaml

    - name: Build SAM Application (no deploy)
      if: github.ref != 'refs/heads/main'
      run: sam build
    