name: SAM Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1 

    - name: Install SAM CLI
      run: |
        curl -L "https://github.com/aws/aws-cli/archive/2.x.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws-cli-2.x/install
        sam --version

    - name: Build and Deploy SAM Application
      if: github.ref == 'refs/heads/main'
      run: |
        sam build
        sam deploy --stack-name DevOpsExam --region eu-west-1 --capabilities CAPABILITY_IAM 

    - name: Build SAM Application (no deploy)
      if: github.ref != 'refs/heads/main'
      run: sam build
